draw_config:
  dark_mode: true
  key_w: 60.0
  key_h: 56.0
  split_gap: 10.0
  combo_w: 50.0
  combo_h: 35.0
  key_rx: 6.0
  key_ry: 6.0
  n_columns: 1
  separate_combo_diagrams: true
  combo_diagrams_scale: 3
  inner_pad_w: 2.0
  inner_pad_h: 2.0
  outer_pad_w: 30.0
  outer_pad_h: 56.0
  line_spacing: 1.2
  arc_radius: 6.0
  append_colon_to_layer_header: true
  small_pad: 2.0
  legend_rel_x: 0.0
  legend_rel_y: 0.0
  draw_key_sides: false
  key_side_pars:
    rel_x: 0
    rel_y: 4
    rel_w: 12
    rel_h: 12
    rx: 4
    ry: 4
  svg_style: |
    /* inherit to force styles through use tags */
    svg path {
        fill: inherit;
    }

    /* font and background color specifications */
    svg.keymap {
        font-family: Monaspace Krypton,Consolas,Liberation Mono,Menlo,monospace;
        font-size: 12px;
        font-kerning: normal;
        text-rendering: optimizeLegibility;
        fill: #24292e;
    }

    /* default key styling */
    rect.key {
        fill: #f6f8fa;
        stroke: #c9cccf;
        stroke-width: 1;
    }

    /* default key side styling, only used is draw_key_sides is set */
    rect.side {
        filter: brightness(90%);
    }

    /* color accent for combo boxes */
    rect.combo, rect.combo-separate {
        fill: #cdf;
    }

    /* color accent for held keys */
    rect.held, rect.combo.held {
        fill: #fdd;
    }

    /* color accent for ghost (optional) keys */
    rect.ghost, rect.combo.ghost {
        stroke-dasharray: 4, 4;
        stroke-width: 2;
    }

    text {
        text-anchor: middle;
        dominant-baseline: middle;
    }

    /* styling for layer labels */
    text.label {
     font-size: 30px;
        font-weight: bold;
        text-anchor: start;
        stroke: white;
        stroke-width: 2;
        paint-order: stroke;
    }

    /* styling for combo tap, and key hold/shifted label text */
    text.combo, text.hold, text.shifted {
        font-size: 11px;
    }

    text.hold {
        text-anchor: middle;
        dominant-baseline: auto;
    }

    text.shifted {
        text-anchor: middle;
        dominant-baseline: hanging;
    }

    /* styling for hold/shifted label text in combo box */
    text.combo.hold, text.combo.shifted {
        font-size: 8px;
    }

    /* lighter symbol for transparent keys */
    text.trans {
        fill: #7b7e81;
    }

    /* styling for combo dendrons */
    path.combo {
        stroke-width: 1;
        stroke: gray;
        fill: none;
    }

    /* Start Tabler Icons Cleanup */
    /* cannot use height/width with glyphs */
    .icon-tabler > path {
        fill: inherit;
        stroke: inherit;
        stroke-width: 2;
    }
    /* hide tabler's default box */
    .icon-tabler > path[stroke="none"][fill="none"] {
        visibility: hidden;
    }
    /* End Tabler Icons Cleanup */
  svg_extra_style: ''
  shrink_wide_legends: 7
  glyph_tap_size: 14
  glyph_hold_size: 12
  glyph_shifted_size: 10
  glyph_urls:
    tabler: https://unpkg.com/@tabler/icons/icons/{}.svg
    mdi: https://raw.githubusercontent.com/Templarian/MaterialDesign-SVG/master/svg/{}.svg
    mdil: https://raw.githubusercontent.com/Pictogrammers/MaterialDesignLight/master/svg/{}.svg
    material: https://fonts.gstatic.com/s/i/short-term/release/materialsymbolsoutlined/{}/default/48px.svg
  use_local_cache: true
parse_config:
  preprocess: true
  skip_binding_parsing: false
  raw_binding_map: {}
  sticky_label: sticky
  toggle_label: toggle
  trans_legend:
    t: '▼'
    type: trans
  mark_alternate_layer_activators: false
  qmk_remove_keycode_prefix:
  - KC_
  qmk_keycode_map:
    SL_INDX: "Index"
    SL_MDLE: "Middle"
    SL_RING: "Ring"
    SL_PNKY: "Pinky"
    SL_STEP: "Cycle"
    ASST: "Assist"
    GMIL: "gmail"
    RGX_NCG: "(?:)"
    PNTROPT: "Opt"
    MLTI: "Multi"

    MI_BACK: "Back"
    MI_DOWN: "Crouch"
    MI_JUMP: "Jump"
    MI_FRNT: "Forward"
    UP__DIR: "../"
    DBSL: "\\"
    DSLH: "//"
    DAMP: "**"
    DPIP: "||"
    PSCR: "Print Screen"
    DBCL: "Double Click"
    BTN1: "Left Click"
    BTN2: "Right Click"
    BTN3: "Scroll Wheel Click"
    SD__MOD: "Snipe DPI Up"
    SD_RMOD: "Snipe DPI Down"
    DPI_MOD: "DPI Up"
    DPI_RMD: "DPI Down"
    SCRL: "Scroll Lock"
    PAUS: "Pause"
    BSPC: "BSpc"
    PSLS: "/"
    P7: "7"
    P8: "8"
    P9: "9"
    PAST: "*"
    INS: "Insert"
    HOME: "Home"
    PGUP: "Page Up"
    P4: "4"
    P5: "5"
    P6: "6"
    DEL: "Delete"
    END: "End"
    PGDN: "Page Down"
    LR_LOCK: "Layer Lock"
    P0: "0"
    F1: "F0b1"
    F2: "F0b2"
    F3: "F0b4"
    F4: "F0b8"
    F5: "F0b16"
    MSEL: "Launch"
    MRWD: "Rwind"
    BRID: "Bright"
    BRIU: "Dim"
    MFFD: "Next"
    MPLY: "Plause"
    MPRV: "Prev"
    VOLU: "Vol Up"
    VOLD: "Vol Down"
    MNXT: "Next"
    MSTP: "Stop"
    MUTE: "Mute"
    KC_CAPS: "Caps Lock"
    EXP_AND: ""
    KC_PDOT: "."
    KC_CEQL: ":="
    SPC: "Space"
    SKP_GRM: "Skip gram"
    ELIP: "..."
    LGCM: "{{/*"
    RGCM: "/*}}"
    RGX_PLB: "(?<=)"
    RGX_NLA: "(?!)"
    DTGV: ".gov"
    DTCM: ".com"
    HOM_DIR: "~/"
    RGX_NCP: "(?:)"
    RGX_NLB: "(?<!)"
    RGX_PLA: "(?=)"
    DGSC: "Drag Scroll"
    SNPE: "Sniping"
    P00: "00"
    P1: "1"
    P2: "2"
    P3: "3"
    PENT: "Enter"
    NG_ATE: "ate"
    NG_ANCE: "ance"
    NG_BL: "bl"
    NG_BY: "by"
    NG_COM: "com"
    NG_CON: "con"
    NG_DON: "don"
    NG_DAY: "day"
    NG_ERS: "ers"
    NG_FRO: "fro"
    NG_FUL: "ful"
    NG_GER: "ger"
    NG_GRE: "gre"
    NG_HER: "her"
    NG_HEA: "hea"
    NG_IN: "in"
    NG_ING: "ing"
    NG_JOY: "joy"
    NG_JECT: "ject"
    NG_KNO: "kno"
    NG_CK: "ck"
    NG_LIN: "lin"
    NG_LEA: "lea"
    NG_MAN: "man"
    NG_MEN: "men"
    NG_NTI: "nti"
    NG_NTE: "nte"
    NG_OME: "ome"
    NG_ONE: "one"
    NG_PRO: "pro"
    NG_PLA: "pla"
    NG_QUA: "qua"
    NG_QUE: "que"
    NG_RAT: "rat"
    NG_STR: "str"
    NG_STI: "sti"
    NG_TER: "ter"
    NG_TED: "ted"
    NG_UST: "ust"
    NG_ULD: "uld"
    NG_VES: "ves"
    NG_VEN: "ven"
    NG_WAY: "way"
    NG_WAS: "was"
    NG_XPL: "xpl"
    NG_XPE: "xpe"
    NG_YTH: "yth"
    NG_YEA: "yea"
    NG_ZED: "zed"


    XXXXXXX: ''
    'NO': ''
    MINUS: '-'
    EQUAL: '='
    TILD: '~'
    LEFT_BRACKET: '['
    RIGHT_BRACKET: ']'
    BACKSLASH: \
    BSLS: \
    NONUS_HASH: '#'
    NUHS: '#'
    SEMICOLON: ;
    SCLN: ;
    QUOTE: ''''
    GRAVE: '`'
    SLASH: /
    PT_SLSH: /
    TILDE: '~'
    EXCLAIM: '!'
    EXLM: '!'
    AT: '@'
    HASH: '#'
    DOLLAR: $
    DLR: $
    PERCENT: '%'
    PERC: '%'
    CIRCUMFLEX: ^
    CIRC: ^
    AMPERSAND: '&'
    ASTERISK: '*'
    ASTR: '*'
    LEFT_PAREN: (
    RIGHT_PAREN: )
    UNDERSCORE: _
    UNDS: _
    PLUS: +
    LEFT_CURLY_BRACE: '{'
    RIGHT_CURLY_BRACE: '}'
    DOUBLE_QUOTE: '"'
    DQUO: '"'
    DQT: '"'
    LEFT_ANGLE_BRACKET: <
    LT: <
    RIGHT_ANGLE_BRACKET: '>'
    GT: '>'
    QUESTION: '?'
    QUES: '?'
  zmk_remove_keycode_prefix: []
  zmk_keycode_map:
    EXCLAMATION: '!'
    EXCL: '!'
    AT_SIGN: '@'
    AT: '@'
    HASH: '#'
    POUND: '#'
    DOLLAR: $
    DLLR: $
    PERCENT: '%'
    PRCNT: '%'
    CARET: ^
    AMPERSAND: '&'
    AMPS: '&'
    ASTERISK: '*'
    ASTRK: '*'
    STAR: '*'
    LEFT_PARENTHESIS: (
    LPAR: (
    RIGHT_PARENTHESIS: )
    RPAR: )
    EQUAL: '='
    PLUS: +
    MINUS: '-'
    UNDERSCORE: _
    UNDER: _
    SLASH: /
    FSLH: /
    QUESTION: '?'
    QMARK: '?'
    BACKSLASH: \
    BSLH: \
    PIPE: '|'
    NON_US_BACKSLASH: \
    PIPE2: '|'
    NON_US_BSLH: '|'
    SEMICOLON: ;
    SEMI: ;
    COLON: ':'
    SINGLE_QUOTE: ''''
    SQT: ''''
    APOSTROPHE: ''''
    APOS: ''''
    DOUBLE_QUOTES: '"'
    DQT: '"'
    COMMA: ','
    LESS_THAN: <
    LT: <
    PERIOD: .
    DOT: .
    GREATER_THAN: '>'
    GT: '>'
    LEFT_BRACKET: '['
    LBKT: '['
    LEFT_BRACE: '{'
    LBRC: '{'
    RIGHT_BRACKET: ']'
    RBKT: ']'
    RIGHT_BRACE: '}'
    RBRC: '}'
    GRAVE: '`'
    TILDE: '~'
    NON_US_HASH: '#'
    NUHS: '#'
    TILDE2: '~'
  zmk_combos: {}
