name: Draw Keymaps

on:
  push:
    branches:
      - main  # Change this to the branch you want to trigger the workflow on

jobs:
  draw-keymaps:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'  # Ensure this matches the Python version you need

      - name: Install keymap-drawer
        run: |
          pip install keymap-drawer

      - name: Run keymap-drawer for keymap.yaml
        run: |
          keymap -c ./keyboards/bastardkb/charybdis/3x6/keymaps/brainrot/config.yaml draw ./keyboards/bastardkb/charybdis/3x6/keymaps/brainrot/keymap.yaml > ./keyboards/bastardkb/charybdis/3x6/keymaps/brainrot/keymap.svg

      - name: Run keymap-drawer for keymapDesign.yaml
        run: |
          keymap -c ./keyboards/bastardkb/charybdis/3x6/keymaps/brainrot/config.yaml draw ./keyboards/bastardkb/charybdis/3x6/keymaps/brainrot/keymapDesign.yaml > ./keyboards/bastardkb/charybdis/3x6/keymaps/brainrot/keymapDesign.svg

      - name: Commit and push updated SVG files
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add ./keyboards/bastardkb/charybdis/3x6/keymaps/brainrot/keymap.svg
          git add ./keyboards/bastardkb/charybdis/3x6/keymaps/brainrot/keymapDesign.svg
          git commit -m "Update keymap SVGs"
          git push
